name: Generate a release

on:
  workflow_run:
    branches: [master, main]
    workflows: ["Check code health"]
    types:
      - completed

jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run:  yarn add semantic-release @semantic-release/changelog @semantic-release/git

      - name: Generate a release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  Docker:
    name: Docker image
    needs: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v4

      - name: Build an image from Dockerfile
        run: make docker-build
